# Generated by Django 3.2.7 on 2021-10-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroom',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
