# Generated by Django 3.2.7 on 2021-10-01 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesInMeetingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ManyToManyField(to='employees.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingRoomReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.employeesinmeetingroom')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='rooms.meetingroom')),
            ],
        ),
    ]
