# Generated by Django 3.2.7 on 2021-10-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='employees',
            field=models.ManyToManyField(blank=True, to='employees.Employee'),
        ),
    ]
